### ISSUE TITLE
Get text content of a node

### ISSUE THREAD

**Issue by bibixx** [figma/code-snippet-editor-plugin#1]
Hi, is there an option to get the contents of the text contents of a node ([characters](https://www.figma.com/plugin-docs/api/properties/TextNode-characters/) property I guess)?

Also supposing I have a component build like this, even if we got the access to the `characters`, would it correctly get the contents of the `Button` layer?
![CleanShot 2023-12-14 at 16 45 50](https://github.com/figma/code-snippet-editor-plugin/assets/14880213/209b855d-7ec5-4489-9fe7-e44089193c4e)

If those aren't possible now but are technically viable (I haven't worked with Figma APIs too much so I'm not sure) then I'm happy to contribute and create a Pull request for those

**Comment by jake-figma** [comment]
there currently isnt functionality for this in the language. the assumption is that the text would be mapped to a text property if it was ever meant to be rendered in code like this.

i am thinking over ways to allow children and their properties to be queryable (see #6), but my recommendation for this specific scenario would be to turn this into a component property on your button component instead of an override in your Figma component instances.
