### ISSUE TITLE
Old instances of component not updated with snippet

### ISSUE THREAD

**Issue by damalekguide** [figma/code-snippet-editor-plugin#33]
Hello :)
I have one simple question.
I added very simple snippet for button. I see the snippet for newly created instances of button but I'm not seeing anything on old components ("No snippets on this node. Add snippets via the Snippet Editor.")

**Comment by jake-figma** [comment]
This sounds like you need to pull in component library changes into your files. There should be a popup in the corner of Figma requesting you review changes to the library (theres a dismiss button which you may have clicked). Youll need to pull those changes in in order to get the updates you made to the main components. This is an limitation of Figma which is ensuring updates to designs arent automatically forced on files by library changes.

More on library updates can be found [in the Figma help center](https://help.figma.com/hc/en-us/articles/360039234193-Review-and-accept-library-updates).
