### ISSUE TITLE
Unable to retrieve parameters from figma.mixed node.textStyle

### ISSUE THREAD

**Issue by mikeysouthwell** [figma/code-snippet-editor-plugin#53]
I am trying to output text to code using the plugin, but it doesn't work when some of the text is Bold for example. It just says the style is figma.mixed. How do I output this as different text blocks? 

I am aware that the current textbox could be easily separated into two (stacked vertically), but often this isn't the case and they need to create a seemless paragraph with normal text and bold text being side-by-side and wrapping inside the frame/autolayout they are contained in. Is there a way to pickup the different sections of the text related to each style being applied or is there a way you can have text boxes fill and wrap inside an autolayout so that they look just like a single textbox?

![image](https://github.com/figma/code-snippet-editor-plugin/assets/32289412/d0d877a1-77b0-4c26-9dce-8788256cff35)

**Comment by mikeysouthwell** [comment]
There is a discussion on this topic in the Figma forums here and I was wondering if you have a workaround:

https://forum.figma.com/t/ability-to-auto-layout-two-text-nodes-as-one-block-of-text-flowing-continuously/44109

**Comment by jake-figma** [comment]
Yeah, there isn't a great way to model this because it can get very complicated. You could theoretically have hundreds of styles in the same text node. We are leaving it at what the plugin API provides at the node level, without any text range traversal. The recommendation is to detect the scenario where it is mixed, and render a default style name instead.
