### ISSUE TITLE
figma.children

### ISSUE THREAD

**Issue by gossi** [figma/code-snippet-editor-plugin#6]
That's a great extension. Especially since it supports _all_ sort of code (not only the react people) - thanks a lot for that.

In my design system, I make great use of slots (instance swap properties).

For example, for a button there is a `before` and `after` slot, which when visible defaults to icons. Now, these icons are their own component, with their own code snippets.

So I was wondering, if there can be a helper to render the snippet of a sub-component ?

**Comment by jake-figma** [comment]
this is a great idea and something i'm currently thinking over supporting! my current thought is to allow you to write `{{figma.children}}` where you want to place the children. a filter of some kind would allow you to select specific children, perhaps by name? eg. `{{figma.children|specific-child-name}}`.

**Comment by jake-figma** [comment]
even a query syntax? `{{figma.children?name=something}}` `{{figma.children.characters?type=text}}`

**Comment by lewishealey** [comment]
Hey Jake! `{{figma.children}}` would work great for us in our API and the specific child names too. We have a tooltip component that would be great to render the component from the snippet attached.

Our expected schema would be:

` <Tooltip content={{property.content}}>
    {(tooltipProps) => (
      {{property.children|slot}}
    )}
  </Tooltip>`

Queries would help too as you may need text too

![Screenshot 2024-01-23 at 1 16 08 pm](https://github.com/figma/code-snippet-editor-plugin/assets/5084186/43c220a4-3232-4241-aba3-ef5f19320e42)
![Screenshot 2024-01-23 at 1 16 13 pm](https://github.com/figma/code-snippet-editor-plugin/assets/5084186/d90a79cb-7f7b-4bd8-bac0-a599927e4ea2)

**Comment by jake-figma** [comment]
One thing we would want to do for this is to make sure that nodes with multiple snippet templates render the _right_ snippet template for a child.

If i have a React and a Vue template, the figma.children in the react template would only render a child template if it too was a react template.

I think the only way to do that would be to check the title of the snippet and make sure they are the same. String matching is kinda gross, but I dont have a better idea right now. Unless you wrote the template title in the figma.children syntax? eg. `{{figma.children?template=React}}`.

Something to consider...

**Comment by jake-figma** [comment]
First draft of this is in with #28. Documentation of this iteration can be found in the ["Children" section in the README](https://github.com/figma/code-snippet-editor-plugin#children).

Closing for now, but open to discussion on improving this moving forward.

**Comment by ericandrewscott** [comment]
Are there any plans to make `{{figma.children}}` recursive instead of just immediate children? For instance, a lot of times we have autolayout frames in between the component and subcomponent. See an example below, where a Badge has either a large or small version as a subcomponent, and each of those have another subcomponent of the actual text, but the large and small subcomponents have an autolayout layer in between the variant and the text, as sibling components to  this could be icon+text or icon only.
<img width="640" alt="Screenshot 2024-02-20 at 10 34 34 AM" src="https://github.com/figma/code-snippet-editor-plugin/assets/1651613/9b7713a3-8027-4e38-8c1a-51da193b35b8">

Also for this reason, an `each` would also be great, especially where the markup of the composed component would be:
```
<ContainerComponent>
    <Subcomponent>Something</Subcomponent>
    <Subcomponent>Something else</Subcomponent>
    <Subcomponent>A third</Subcomponent>
</ContainerComponent>
```

@jake-figma is this something you would accept a PR for?

**Comment by jake-figma** [comment]
@ericandrewscott, i'm trying to keep this as light as possible at the moment. the immediate child limitation is one way to keep things snappy. one thing id consider is an approach that targets specific nodes (whether with query params or specifying a level to dig to), however i think what youre trying todo is already supported. you just need to add a template to the inbetween `Text only` frame.

```
  {{figma.children}}
```

on that frame is the intended way to extend this.

**Comment by ericandrewscott** [comment]
Totally get keeping it light. I think the population of nesting changes to include:

1. Parent component set with `{{figma.children}}` in some part of the template.
2. Adding `{{figma.children}}` to child nodes of every variant in that parent component set. (in our case it's only 2 or 3, but multiply that by the number of variants in the set, and it can get pretty tedious.
3. Adding template to the nested child nodes where text, icon, etc markup bubbles up from.

Is `{{#each}}` something you're still considering?

**Comment by jake-figma** [comment]
one of the strengths of the language right now is that each line is evaluated in isolation making it very easy to process quickly and fail gracefully which makes me hesitant to include any sort of block syntax for "each" or "if".

a working solution for the hypothetical youre describing would be to make the child frame a component so that the instance frames would share the same template. ideally if theres a pattern, it is accounted for somehow in figma and not just implied.

in terms of additions to cover "each" logic, one option im thinking through is the ability to put global template definitions on a component. what that would mean is the ability to hang a "FRAME" child template (or any node type) on the main component itself.

**Comment by ericandrewscott** [comment]
In the meantime, like you said, I can totally get around it by throwing `{{figma.children}}` on the intermediary nodes that are frames, or doing things like:
```
<List bullet="no-bullet" orientation="inline">
    {{figma.children}}
</List>
```
on specific frames, which can be tedious if you're digging through each variant as opposed to adding it dynamically to a component set.

I think the interesting thing is that it does highlight any cruft in the way design components are built!
